name: Build with Maven and generate reports

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: |
        mvn -B clean package --file pom.xml || echo "BUILD FAILED" > build_failed.flag

    - name: Upload coverage to Coveralls
      if: always()
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: mvn coveralls:report

    - name: Generate Checkstyle report
      run: mvn checkstyle:checkstyle

    - name: Create site
      if: always()
      run: mvn site

    - name: Ensure index.html exists
      if: always()
      run: |
        if [ ! -f target/site/index.html ]; then
          echo "<html><body><h1>Report Index</h1></body></html>" > target/site/index.html
        fi

    - name: Upload Checkstyle report as artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: checkstyle-report
        path: target/checkstyle-*.xml

    - name: Deploy report to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/site

    - name: Fail job if build failed
      if: failure()
      run: |
        echo "Build failed"
        exit 1
